apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: test-configuration
spec:
  crossplane:
    version: ">=v1.16.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-aws
      version: ">=v1.9.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-dynamodb
      version: ">=v1.9.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v1.9.0"
